import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "./convex/ConvexClientProvider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";

const geistSans = Geist({
        variable: "--font-geist-sans",
        subsets: ["latin"],
});

const geistMono = Geist_Mono({
        variable: "--font-geist-mono",
        subsets: ["latin"],
});

export const metadata: Metadata = {
        title: "Clerk Next.js Quickstart",
        description: "Generated by create next app",
};

export default function RootLayout({
        children,
}: Readonly<{
        children: React.ReactNode;
}>) {
        return (
                <html lang="en">
                        <body
                                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                        >
                                <ConvexClientProvider>
                                        <SidebarProvider>
                                                <AppSidebar />
                                                <main className="p-4">
                                                        <SidebarTrigger />
                                                        {children}
                                                </main>
                                        </SidebarProvider>
                                </ConvexClientProvider>
                        </body>
                </html>
        );
}
